import { Layout } from "antd";
import "../globals.css";
import HeaderWrapper from "@/components/client/layout/HeaderWrapper";
import FooterWrapper from "@/components/client/layout/FooterWrapper";
import { AuthProvider } from "@/context/AuthContext";
import { QRDesignProvider } from "@/context/QRDesignContext";
import { ContactProvider } from "@/context/ContactCardContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        {/* Google meta tags */}
        <meta name="google-signin-client_id" content="" />
        <meta name="google-signin-scope" content="" />
      </head>
      <body>
        <AuthProvider>
          <QRDesignProvider>
            <ContactProvider>
              <Layout style={{ minHeight: "100vh" }}>
                <HeaderWrapper />
                {children}
                <FooterWrapper />
              </Layout>
            </ContactProvider>
          </QRDesignProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
